services:
  web:
    image: josefjebavy/debian-apache-php8.0-nette
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - .docker/mysql:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080

  composer:
    image: composer
    command: [ "composer", "install" ]
    volumes:
      - .:/app
